title: Estelle Tourillon
author: EstelleTrln
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Développeuse Web Junior, passionnée d'Art et de Littérature j'espère partager et apporter ces passions avec moi dans la sphère numérique. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  EstelleTrln # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
